package com.alibaba.shuaishuai.DO;

public class Adress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_adress.id
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_adress.company
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_adress.home
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    private String home;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_adress.name
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_adress.id
     *
     * @return the value of person_adress.id
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_adress.id
     *
     * @param id the value for person_adress.id
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_adress.company
     *
     * @return the value of person_adress.company
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_adress.company
     *
     * @param company the value for person_adress.company
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_adress.home
     *
     * @return the value of person_adress.home
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    public String getHome() {
        return home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_adress.home
     *
     * @param home the value for person_adress.home
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    public void setHome(String home) {
        this.home = home == null ? null : home.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_adress.name
     *
     * @return the value of person_adress.name
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_adress.name
     *
     * @param name the value for person_adress.name
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}