package com.alibaba.shuaishuai.DO;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hehe.id
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hehe.name
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hehe.age
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hehe.time
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hehe.id
     *
     * @return the value of hehe.id
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hehe.id
     *
     * @param id the value for hehe.id
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hehe.name
     *
     * @return the value of hehe.name
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hehe.name
     *
     * @param name the value for hehe.name
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hehe.age
     *
     * @return the value of hehe.age
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hehe.age
     *
     * @param age the value for hehe.age
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hehe.time
     *
     * @return the value of hehe.time
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hehe.time
     *
     * @param time the value for hehe.time
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }

    @Override
    public String toString() {
        return "User{" +
            "id=" + id +
            ", name='" + name + '\'' +
            ", age=" + age +
            ", time=" + time +
            '}';
    }
}