/**
 * Alibaba.com Inc.
 * Copyright (c) 1999-2022 All Rights Reserved.
 */
package com.alibaba.shuaishuai.model;

import java.util.Date;
import java.util.List;

import lombok.Data;

/**
 * @author linYue
 * @version TwoAdressVO.java, v 0.1 2022年08月15日 2:45 PM linYue Exp $
 */

@Data
public class TwoAdressVO {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hehe.age
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hehe.time
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_adress.company
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    private List<String> companyList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_adress.home
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    private List<String> homeList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_adress.name
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    private String name;
}