/**
 * Alibaba.com Inc.
 * Copyright (c) 1999-2022 All Rights Reserved.
 */
package com.alibaba.shuaishuai.model;

import java.util.Date;

import lombok.Data;

/**
 * @author linYue
 * @version UserVO.java, v 0.1 2022年08月14日 9:02 PM linYue Exp $
 */

@Data
public class UserVO {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hehe.name
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hehe.age
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    private Integer age;





}