package com.alibaba.shuaishuai.dao;

import com.alibaba.shuaishuai.DO.Adress;
import com.alibaba.shuaishuai.DO.AdressExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AdressDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_adress
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    long countByExample(AdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_adress
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    int deleteByExample(AdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_adress
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_adress
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    int insert(Adress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_adress
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    int insertSelective(Adress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_adress
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    List<Adress> selectByExample(AdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_adress
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    Adress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_adress
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    int updateByExampleSelective(@Param("record") Adress record, @Param("example") AdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_adress
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    int updateByExample(@Param("record") Adress record, @Param("example") AdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_adress
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    int updateByPrimaryKeySelective(Adress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_adress
     *
     * @mbg.generated Mon Aug 15 14:43:22 CST 2022
     */
    int updateByPrimaryKey(Adress record);
}