package com.alibaba.shuaishuai.dao;

import com.alibaba.shuaishuai.DO.User;
import com.alibaba.shuaishuai.DO.UserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hehe
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hehe
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hehe
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hehe
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hehe
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hehe
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hehe
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hehe
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hehe
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hehe
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hehe
     *
     * @mbg.generated Fri Aug 12 17:04:55 CST 2022
     */
    int updateByPrimaryKey(User record);
}